### PR TITLE
Pre-compress JS and CSS with gzip in release build

### PR DESCRIPTION
**Pull request by drigz**
Also builds static resources into the OpenRobertaServer JAR rather than
using a separate directory.

To use the release build, pass -Prelease to mvn.

This reduces the page size from about 2.3 MiB to about 800 KiB. This
should improve #56.

### CODE REVIEW

**Comment by drigz** [comment]
Note: I haven't tested running exported builds because they crash with an `ILightSensorMode cannot be resolved to a type` error for me.

**Comment by drigz** [comment]
That error stopped happening, it must have been something weird in my local build state. Steps to export:

cd OpenRobertaParent
mvn clean install
cd ..
./ora.sh --export -e installDir
cd installDir
./ora.sh --start-server

You should then be able to access it from your browser and test out the change. If you press Ctrl+Shift+I (in Chrome) to open the inspector then open the Network tab and hit refresh, you should see that now about 800KB are loaded.

**Comment by bjost2s** [comment]
we have a build server installed here in the institute and since this morning it is not available anymore.
This server starts automatically with ./ora.sh --start-server
Please try to make it run again, because other members of the team are working with this.

**Comment by drigz** [comment]
I can't revert the PR because I don't have access. Instructions: https://help.github.com/articles/reverting-a-pull-request/

Sorry about the build break! Do you have any more information about the failure? ./ora.sh --start-server works for me, but if I can reproduce I'll resubmit the PR after fixing the issue.

**Comment by bjost2s** [comment]
I just pullt develop and did successfully a mvn clean install. Then starting the server :+1: 
beate@mp-mobil-06:~/OpenRoberta/robertalab$ ./ora.sh --start-server
starting the server from a git repository. Using openRoberta.properties from the classpath
you are using the following java runtime:
java version "1.7.0_79" Java(TM) SE Runtime Environment (build 1.7.0_79-b15) Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)
RUNNING OPEN ROBERTA LAB FROM A GIT REPOSITORY WITHOUT AN EXPLICIT EXPORT. THIS MAY BE DANGEROUS!
executing: java -cp target/resources/\* de.fhg.iais.roberta.main.ServerStarter --port 1999
14:14:56.870 [main] INFO de.fhg.iais.roberta.util.Util1 - properties from classpath. Using the resource: openRobertaMailServer.properties
14:14:56.873 [main] INFO de.fhg.iais.roberta.util.Util1 - properties from classpath. Using the resource: openRoberta.properties
14:14:56.894 [main] INFO org.eclipse.jetty.util.log - Logging initialized @286ms
14:14:56.933 [main] INFO d.f.i.r.r.RobotCommunicator - timer thread created
14:14:56.946 [main] INFO de.fhg.iais.roberta.util.Util1 - properties from classpath. Using the resource: SIM.properties
14:14:56.950 [main] INFO de.fhg.iais.roberta.util.Util1 - properties from classpath. Using the resource: NXT.properties
14:14:56.956 [main] INFO de.fhg.iais.roberta.util.Util1 - properties from classpath. Using the resource: EV3.properties
14:14:56.958 [main] INFO d.f.iais.roberta.main.ServerStarter - ROBOT PLUGINS: 3 plugins are found: ev3 oraSim nxt 
14:14:56.998 [main] WARN o.e.j.server.handler.ContextHandler - o.e.j.s.ServletContextHandler@24d1f5ed{/,null,null} contextPath ends with /*
14:14:56.999 [main] WARN o.e.j.server.handler.ContextHandler - Empty contextPath
14:14:57.004 [main] INFO org.eclipse.jetty.server.Server - jetty-9.2.17.v20160517
Jul 18, 2016 2:14:57 PM com.sun.jersey.api.core.PackagesResourceConfig init
INFO: Scanning for root resource and provider classes in the packages:
  de.fhg.iais.roberta.javaServer.restServices.all
  de.fhg.iais.roberta.javaServer.restServices.robot
  de.fhg.iais.roberta.javaServer.provider
Jul 18, 2016 2:14:57 PM com.sun.jersey.api.core.ScanningResourceConfig logClasses
INFO: Root resource classes found:
  class de.fhg.iais.roberta.javaServer.restServices.robot.RobotDownloadProgram
  class de.fhg.iais.roberta.javaServer.restServices.robot.Ev3Update
  class de.fhg.iais.roberta.javaServer.restServices.all.RestExample
  class de.fhg.iais.roberta.javaServer.restServices.all.ClientPing
  class de.fhg.iais.roberta.javaServer.restServices.robot.RobotSensorLogging
  class de.fhg.iais.roberta.javaServer.restServices.all.ClientAdmin
  class de.fhg.iais.roberta.javaServer.restServices.all.ClientUser
  class de.fhg.iais.roberta.javaServer.restServices.all.Alive
  class de.fhg.iais.roberta.javaServer.restServices.all.ClientToolbox
  class de.fhg.iais.roberta.javaServer.restServices.all.ClientConfiguration
  class de.fhg.iais.roberta.javaServer.restServices.all.ClientProgram
  class de.fhg.iais.roberta.javaServer.restServices.robot.RobotCommand
Jul 18, 2016 2:14:57 PM com.sun.jersey.api.core.ScanningResourceConfig logClasses
INFO: Provider classes found:
  class de.fhg.iais.roberta.javaServer.provider.JAXBContextProvider
  class de.fhg.iais.roberta.javaServer.provider.OraDataProvider
  class de.fhg.iais.roberta.javaServer.provider.JAXBUnmarshallerProvider
  class de.fhg.iais.roberta.javaServer.provider.JAXBMarshallerProvider
Jul 18, 2016 2:14:57 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
INFO: Registering de.fhg.iais.roberta.javaServer.restServices.all.ClientAdmin as a root resource class
Jul 18, 2016 2:14:57 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
INFO: Registering de.fhg.iais.roberta.javaServer.restServices.all.ClientConfiguration as a root resource class
Jul 18, 2016 2:14:57 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
INFO: Registering de.fhg.iais.roberta.javaServer.restServices.all.ClientToolbox as a root resource class
Jul 18, 2016 2:14:57 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
INFO: Registering de.fhg.iais.roberta.javaServer.restServices.all.ClientProgram as a root resource class
Jul 18, 2016 2:14:57 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
INFO: Registering de.fhg.iais.roberta.javaServer.restServices.all.ClientUser as a root resource class
Jul 18, 2016 2:14:57 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
INFO: Registering de.fhg.iais.roberta.javaServer.restServices.robot.RobotDownloadProgram as a root resource class
Jul 18, 2016 2:14:57 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
INFO: Registering de.fhg.iais.roberta.javaServer.restServices.robot.RobotCommand as a root resource class
Jul 18, 2016 2:14:57 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
INFO: Registering de.fhg.iais.roberta.javaServer.restServices.robot.RobotSensorLogging as a root resource class
Jul 18, 2016 2:14:57 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
INFO: Registering de.fhg.iais.roberta.javaServer.restServices.all.RestExample as a root resource class
Jul 18, 2016 2:14:57 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
INFO: Registering de.fhg.iais.roberta.javaServer.restServices.all.ClientPing as a root resource class
Jul 18, 2016 2:14:57 PM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
INFO: Initiating Jersey application, version 'Jersey: 1.18.2 10/26/2014 03:51 PM'
Jul 18, 2016 2:14:57 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
INFO: Binding de.fhg.iais.roberta.javaServer.provider.OraDataProvider to GuiceInjectedComponentProvider
14:14:58.044 [main] INFO o.h.annotations.common.Version - HCANN000001: Hibernate Commons Annotations {4.0.2.Final}
14:14:58.048 [main] INFO org.hibernate.Version - HHH000412: Hibernate Core {4.2.7.Final}
14:14:58.049 [main] INFO org.hibernate.cfg.Environment - HHH000206: hibernate.properties not found
14:14:58.050 [main] INFO org.hibernate.cfg.Environment - HHH000021: Bytecode provider name : javassist
14:14:58.065 [main] INFO org.hibernate.cfg.Configuration - HHH000043: Configuring from resource: hibernate-cfg.xml
14:14:58.065 [main] INFO org.hibernate.cfg.Configuration - HHH000040: Configuration resource: hibernate-cfg.xml
14:14:58.105 [main] INFO org.hibernate.cfg.Configuration - HHH000041: Configured SessionFactory: null
14:14:58.146 [main] INFO o.h.s.j.c.i.ConnectionProviderInitiator - HHH000130: Instantiating explicit connection provider: org.hibernate.service.jdbc.connections.internal.C3P0ConnectionProvider
14:14:58.147 [main] INFO o.h.s.j.c.i.C3P0ConnectionProvider - HHH010002: C3P0 using driver: org.hsqldb.jdbcDriver at URL: jdbc:hsqldb:file:db/openroberta-db
14:14:58.147 [main] INFO o.h.s.j.c.i.C3P0ConnectionProvider - HHH000046: Connection properties: {user=orA, password=****, autocommit=false}
14:14:58.147 [main] INFO o.h.s.j.c.i.C3P0ConnectionProvider - HHH000006: Autocommit mode: false
Jul 18, 2016 2:14:58 PM com.mchange.v2.log.MLog <clinit>
INFO: MLog clients using java 1.4+ standard logging.
Jul 18, 2016 2:14:58 PM com.mchange.v2.c3p0.C3P0Registry banner
INFO: Initializing c3p0-0.9.2.1 [built 20-March-2013 10:47:27 +0000; debug? true; trace: 10]
Jul 18, 2016 2:14:58 PM com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource getPoolManager
INFO: Initializing c3p0 pool... com.mchange.v2.c3p0.PoolBackedDataSource@b117a7eb [ connectionPoolDataSource -> com.mchange.v2.c3p0.WrapperConnectionPoolDataSource@eb265e54 [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, debugUnreturnedConnectionStackTraces -> false, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, identityToken -> z8kfsx9h1ygfy4lk8g9sh|1a66421c, idleConnectionTestPeriod -> 3600, initialPoolSize -> 5, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 7200, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 100, maxStatements -> 100, maxStatementsPerConnection -> 0, minPoolSize -> 5, nestedDataSource -> com.mchange.v2.c3p0.DriverManagerDataSource@fd895e16 [ description -> null, driverClass -> null, factoryClassLocation -> null, identityToken -> z8kfsx9h1ygfy4lk8g9sh|7ba75fd0, jdbcUrl -> jdbc:hsqldb:file:db/openroberta-db, properties -> {user=******, password=******, autocommit=false} ], preferredTestQuery -> null, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, usesTraditionalReflectiveProxies -> false; userOverrides: {} ], dataSourceName -> null, factoryClassLocation -> null, identityToken -> z8kfsx9h1ygfy4lk8g9sh|15f1192d, numHelperThreads -> 3 ]
2016-07-18T14:15:08.793+0200  SEVERE  could not reopen database
org.hsqldb.HsqlException: Database lock acquisition failure: lockFile: org.hsqldb.persist.LockFile@8ae910e1[file =/home/beate/OpenRoberta/robertalab/OpenRobertaServer/db/openroberta-db.lck, exists=true, locked=false, valid=false, ] method: checkHeartbeat read: 2016-07-18 12:15:07 heartbeat - read: -8735 ms.
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.persist.LockFile.newLockFileLock(Unknown Source)
	at org.hsqldb.persist.Logger.acquireLock(Unknown Source)
	at org.hsqldb.persist.Logger.open(Unknown Source)
	at org.hsqldb.Database.reopen(Unknown Source)
	at org.hsqldb.Database.open(Unknown Source)
	at org.hsqldb.DatabaseManager.getDatabase(Unknown Source)
	at org.hsqldb.DatabaseManager.newSession(Unknown Source)
	at org.hsqldb.jdbc.JDBCConnection.<init>(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.getConnection(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.connect(Unknown Source)
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:146)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:195)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:184)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:200)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1086)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1073)
	at com.mchange.v2.resourcepool.BasicResourcePool.access$800(BasicResourcePool.java:44)
	at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1810)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:648)

**Comment by ensonic** [comment]
@bjost2s please link to the build server if possible or upload a log to a gist / some pastebin.

I just retried:
```
cd OpenRobertaParent
mvn clean install -Prelease
cd ..
./ora.sh --start-server
```
and
```
cd OpenRobertaParent
mvn clean install
cd ..
./ora.sh --start-server
```

**Comment by ensonic** [comment]
@bjost2s did you follow reinhards mail on the database setup?
```
rm -rf OpenRobertaServer/db/
cp -r OpenRobertaServer/dbBase OpenRobertaServer/db
```

**Comment by bjost2s** [comment]
for me it is not a problem, but for our buildserver it is only 
./ora.sh --start-server 
executed as I just tried and this failed since this morning

**Pull request merged**
