### PR TITLE
Fix receive message block (NXT)

### PR DESCRIPTION
**Pull request by simonedegiacomi**
Fixes the same bug described in the issue #1122, but for the receive message block

### CODE REVIEW

**Comment by VinArt** [comment]
Hi @simonedegiacomi, I have taken a look at the pull-request, first, thanks for testing and fixing the problem, but I would like to ask you to change the code a bit before we can merge it directly.

- please add issue number to both commits, or squash them. It becomes harder to find commits for the particular issue when they lack the reference.

- this can later result in an error, that is hard to catch:
```

**Comment by VinArt** [comment]
Hi @simonedegiacomi, I have taken a look at the pull-request, first, thanks for testing and fixing the problem, works nicely now, but I would like to ask you to change the code a bit before we can merge it directly.

- please add issue number to both commits, or squash them. It becomes harder to find commits for the particular issue when they lack the reference.

- this can later result in an error, that is hard to catch:
```
AbstractHelperForXmlTest.java, line 131:
if(!diff.identical())
    System.out.println(diff);
```
this should be enclosed in curly braces or removed, since if the test fails it is exactly due to the diff being not empty.

- if you could also apply our formatter, it would be appreciated.

**Comment by simonedegiacomi** [comment]
Hi, thank you for the reply!


> Hi @simonedegiacomi, I have taken a look at the pull-request, first, thanks for testing and fixing the problem, works nicely now, but I would like to ask you to change the code a bit before we can merge it directly.
> 
>     * please add issue number to both commits, or squash them. It becomes harder to find commits for the particular issue when they lack the reference.
> 
Since the pull reuqest is already open, and to rename the second commit or squash them I would need to change the commit hash, should I make the changes and then open a new pull request? I'm afraid that if I force pull to my develop branch the pull request may broke.
>     * this can later result in an error, that is hard to catch:
> 
> 
> ```
> AbstractHelperForXmlTest.java, line 131:
> if(!diff.identical())
>     System.out.println(diff);
> ```
> 
> this should be enclosed in curly braces or removed, since if the test fails it is exactly due to the diff being not empty.
> 
I agree, I'm going to remove the statement.
>     * if you could also apply our formatter, it would be appreciated.
I should have done that (I use intelliJ and I imported the eclipse style, like it's said in the wiki). I think I forgot to check the "reformat code" checkbox before the commit. I'll adjust that immidietaly.

**Comment by VinArt** [comment]
@simonedegiacomi about the squash and force-push.. I am not sure how github will react to that, maybe one would need to re-open the pull request, it does not matter that much, I guess, so you can do it either way that works.

**Comment by simonedegiacomi** [comment]
I tried to force push on a branch with an existing pull request in a test repository and it seems to have done the right thing. So I force pushed to my develop branch and the pull request got updated

**Pull request merged**
